# Generated by Django 5.0.1 on 2024-01-21 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoas',
            old_name='descricao',
            new_name='descricao_nome',
        ),
    ]
